# Generated by Django 5.1.4 on 2024-12-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username_payments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите Вашу страну",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=35,
                null=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите Ваше фото",
                null=True,
                upload_to="media/users/avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите Ваш e-mail",
                max_length=254,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
