# Generated by Django 5.1.4 on 2025-01-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
